const controls = @import("media/controls.zig");

pub const ICurrentSessionChangedEventArgs = controls.ICurrentSessionChangedEventArgs;
pub const IMediaPropertiesChangedEventArgs = controls.IMediaPropertiesChangedEventArgs;
pub const ITimelinePropertiesChangedEventArgs = controls.ITimelinePropertiesChangedEventArgs;
pub const IGlobalSystemMediaTransportControlsSession = controls.IGlobalSystemMediaTransportControlsSession;
pub const IGlobalSystemMediaTransportControlsSessionManager = controls.IGlobalSystemMediaTransportControlsSessionManager;
pub const IGlobalSystemMediaTransportControlsSessionPlaybackInfo = controls.IGlobalSystemMediaTransportControlsSessionPlaybackInfo;
pub const IGlobalSystemMediaTransportControlsSessionManagerStatics = controls.IGlobalSystemMediaTransportControlsSessionManagerStatics;
pub const IGlobalSystemMediaTransportControlsSessionMediaProperties = controls.IGlobalSystemMediaTransportControlsSessionMediaProperties;
pub const IGlobalSystemMediaTransportControlsSessionTimelineProperties = controls.IGlobalSystemMediaTransportControlsSessionTimelineProperties;
